// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9a7a956e-3e87-4af4-87c4-1f725bd88a57";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDissolvedChange();
void onPhValueChange();
void onStepperVariable1Change();
void onStepperVariable2Change();
void onStepperVariable3Change();
void onStepperVariable4Change();
void onStepperVariable5Change();
void onStepperVariable6Change();
void onTempCelsiusChange();
void onTempFahrenheitChange();
void onMessengerUpdatesChange();
void onServoPushButtonChange();

float dissolved;
float phValue;
float stepperVariable1;
float stepperVariable2;
float stepperVariable3;
float stepperVariable4;
float stepperVariable5;
float stepperVariable6;
float tempCelsius;
float tempFahrenheit;
bool messengerUpdates;
bool servoPushButton;
bool wifiLED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dissolved, READWRITE, ON_CHANGE, onDissolvedChange);
  ArduinoCloud.addProperty(phValue, READWRITE, ON_CHANGE, onPhValueChange);
  ArduinoCloud.addProperty(stepperVariable1, READWRITE, ON_CHANGE, onStepperVariable1Change);
  ArduinoCloud.addProperty(stepperVariable2, READWRITE, ON_CHANGE, onStepperVariable2Change);
  ArduinoCloud.addProperty(stepperVariable3, READWRITE, ON_CHANGE, onStepperVariable3Change);
  ArduinoCloud.addProperty(stepperVariable4, READWRITE, ON_CHANGE, onStepperVariable4Change);
  ArduinoCloud.addProperty(stepperVariable5, READWRITE, ON_CHANGE, onStepperVariable5Change);
  ArduinoCloud.addProperty(stepperVariable6, READWRITE, ON_CHANGE, onStepperVariable6Change);
  ArduinoCloud.addProperty(tempCelsius, READWRITE, ON_CHANGE, onTempCelsiusChange);
  ArduinoCloud.addProperty(tempFahrenheit, READWRITE, ON_CHANGE, onTempFahrenheitChange);
  ArduinoCloud.addProperty(messengerUpdates, READWRITE, ON_CHANGE, onMessengerUpdatesChange);
  ArduinoCloud.addProperty(servoPushButton, READWRITE, ON_CHANGE, onServoPushButtonChange);
  ArduinoCloud.addProperty(wifiLED, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
